services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    env_file:
      - ./.env.development
    ports:
      - 3306:3306
    environment:
      # MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: ${TENANT_DB_PASSWORD}
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    platform: linux/arm64
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    env_file:
      - ./.env.development
    ports:
      - 6379:${REDIS_PORT}
    volumes:
      - ./db/redis/data:/data
