version: '3.9'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    env_file:
      - ./.env
    ports:
      - 3306:3306
    environment:
      # MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    platform: linux/arm64
