services:
  # app:
  #   container_name: nestjs-app
  #   build:
  #     target: development
  #   ports:
  #     - '${APP_PORT:-3100}:3000'
  #   volumes:
  #     - './:/srv/app'

  db-tenant:
    image: mysql:8.4.0
    container_name: nestjs-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '${DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-Pa55w0rd}
      MYSQL_DATABASE: ${DB_NAME:-wms}
      MYSQL_USER: ${DB_USERNAME:-wms}
      MYSQL_PASSWORD: ${DB_PASSWORD:-Pa55w0rd}
    volumes:
      - ./db/mysql/data:/var/lib/mysql
    # platform: linux/arm64

  db-redis:
    image: redis:7.2.5
    container_name: nestjs-redis
    restart: always
    env_file:
      - .env
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - ./db/redis/data:/data
